### ISSUE TITLE
リストのアラインメントがずれている

### ISSUE THREAD

**Issue by takahi-i** [continuous-manual-writing/redpen-doc-ja#18]
リストのアラインメントがずれているのを発見しました。体裁がわるいのでなおしてしまいたいです。

![screen shot 2015-11-18 at 16 31 06](https://cloud.githubusercontent.com/assets/339436/11235129/0354e69e-8e12-11e5-9d93-22867c6f8fec.png)

**Comment by takahi-i** [comment]
@taky ちょっとみてもらえますか？

**Comment by alterakey** [comment]
指摘ありがとうございます！修正に入ります。

**Comment by takahi-i** [comment]
:+1:

**Comment by takahi-i** [comment]
本 Issue はプルリクエスト #19 によって解決されました。
