### ISSUE TITLE
誤記（SectionLength）

### ISSUE THREAD

**Issue by kongou-ae** [continuous-manual-writing/redpen-doc-ja#22]
[SectionLength](https://github.com/continuous-manual-writing/redpen-doc-ja/blob/master/source/validator_ja.adoc#sectionlength)のmax_numプロパティの解説が「一つ節で利用する単語の最大数」になっています。正しくは「一つの節で利用する単語の最大数」だと思います。

**Comment by takahi-i** [comment]
@kongou-ae ありがとうございます。ご指摘いただい点について、修正いたします。

**Comment by alterakey** [comment]
報告ありがとうございます。こちら修正を引き受けます。

**Comment by takahi-i** [comment]
修正したのでクローズさせていただきます。ご報告ありがとうございました。
