### ISSUE TITLE
Travisの検査で最終成果物（PDFなど）が生成できるかも検査したい

### ISSUE THREAD

**Issue by takahi-i** [continuous-manual-writing/redpen-doc-ja#24]
現在Travisの設定では、RedPen の検査だけをおなこっていますが、PDF などの成果物が生成できるかも検査したいと考えています。

**Comment by takahi-i** [comment]
こちらも時間のある時にお願いします @taky。

**Comment by alterakey** [comment]
プルリクエストを出しました。よろしくお願いいたします。

**Comment by takahi-i** [comment]
ありがとうございます！
