### ISSUE TITLE
Javascript拡張の作り方に関する節

### ISSUE THREAD

**Issue by takahi-i** [continuous-manual-writing/redpen-doc-ja#30]
ブログにはJavaScript拡張の作り方に関する記事があるのですが、ドキュメントにありません。リリース前に作成してしまいたいと思っています。
## 参考
- http://www.clear-code.com/blog/2015/8/29.html
- http://blog.redpen.cc/2015/09/08/writing-extension-with-javascript/
- http://atl.recruit-tech.co.jp/blog/3629/

**Comment by alterakey** [comment]
プルリクエストを作成しました。よろしくお願いいたします。

**Comment by takahi-i** [comment]
#31 により解決されました。
