### ISSUE TITLE
.travis.ymlを調整したい

### ISSUE THREAD

**Issue by alterakey** [continuous-manual-writing/redpen-doc-ja#33]
.travis.ymlを調整します。調整する点は以下の3点です。
- バージョン情報出力を削除
- make check html pdf を各ターゲットごとに分解
- 分解した各ターゲットに補足コメントを追加

**Comment by takahi-i** [comment]
おっ、いい変更ですね。

**Comment by takahi-i** [comment]
本イシューは #34 により解決しました。
