### ISSUE TITLE
Spelling 機能のプロパティ

### ISSUE THREAD

**Issue by takahi-i** [continuous-manual-writing/redpen-doc-ja#38]
Spelling 機能がサポートするプロパティに関する説明がないので、追加する必要があります。

参考（英語マニュアル）：https://github.com/redpen-cc/redpen-doc/issues/35

**Comment by alterakey** [comment]
#41にて修正を確認しました。

**Comment by takahi-i** [comment]
ありがとうございます！

2016-03-23 11:19 GMT+09:00 Takahiro Yoshimura notifications@github.com:

> #41にて修正を確認しました。
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/continuous-manual-writing/redpen-doc-ja/issues/38#issuecomment-200134462

## 

Takahiko
