### ISSUE TITLE
スタイルファイルを追加したい

### ISSUE THREAD

**Issue by takahi-i** [continuous-manual-writing/redpen-doc-ja#6]
RedPen ドキュメント用のスタイルファイルを作りたいと考えています。デフォルトスタイルの見栄はいいのですが、RedPenのドキュメントとわかるようにスタイルを変更したいと考えてます。

**Comment by alterakey** [comment]
目下readthedocsスタイルをベースに調整を進めています。以下はスクリーンショットです。
![shot1](https://cloud.githubusercontent.com/assets/303596/11200169/fb30404a-8d16-11e5-9252-08f195bddf90.png)

**Comment by takahi-i** [comment]
おおっ、格好いいですね。ひきつづきよろしくお願いします。

**Comment by taky** [comment]
体裁を若干調整し、ロゴを入れました。以下は最新のスクリーンショットになります。

![shot4](https://cloud.githubusercontent.com/assets/303596/11203096/69786688-8d33-11e5-857e-784f30c37722.png)
![shot5](https://cloud.githubusercontent.com/assets/303596/11203098/6ec90606-8d33-11e5-8c56-7633d059a468.png)

**Comment by takahi-i** [comment]
おおっ、かっこいいですね。その調子でお願いします！

**Comment by takahi-i** [comment]
本 Issue はプルリクエスト #11  によって解決されました。
